#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage update acme"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  export PATH=$PACKAGE_ACME_DIR:$PATH
  acme.sh --upgrade
}

run() {
  core $@
}

run $@
